version: '2'
services:
  mariadb:
    image: mariadb/server:10.3
    ports:
        - "3306:3306"
    volumes:
        - "./var-lib-mysql:/var/lib/mysql"
        - "./mariadb/my.cnf:/etc/mysql/my.cnf"
    environment:
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: root
    restart: always
  nginx:
    image: nginx:1.15
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./html:/var/www/html"
        - "./log/nginx:/var/log/nginx"
    restart: always
  phpfpm:
    image: php:7.3-fpm
    links:
        - mariadb
    volumes:
        - "./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        - "./phpfpm/php.ini:/usr/local/etc/php/php.ini"
        - "./html:/var/www/html"
        - "./log/php:/var/log/php"
    restart: always
